import { StyleSheet } from 'react-native';
import colors from '../../styles/colors';

export const styles = StyleSheet.create({
  containerList: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'column',
    alignItems: 'center',
    listStyle: 'none',
    padding: 15,
    paddingBottom: 50,
  },
  list: {
    fontSize: 16,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    borderRadius: 5,
    width: '90%',
    maxWidth: 800,
    padding: 15,
    borderWidth: 1,
    borderColor: colors.darkGreen,
    margin: 5,
    color: colors.darkGreen,
  },
  wrapper: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 10,
    marginVertical: 5,
    color: colors.darkGreen,
  },
  footer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    backgroundColor: colors.transparent,
    paddingVertical: 15,
    paddingHorizontal: 10,
    position: 'absolute',
    left: 0,
    bottom: 0,
  },
  addBottom: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 5,
    backgroundColor: colors.darkGreen,
    border: 0,
    width: 50,
    height: 50,
    borderRadius: 50,
    textAlign: 'center',
    cursor: 'pointer',
    marginHorizontal: 10,
    boxShadow: 'none',
    marginBottom: 10,
  },
  progressBarContainer: {
    marginTop: 20,
    paddingVertical: 10,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  progressBarText: {
    marginHorizontal: 10,
  },
});
